require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)
task :default => :spec

desc "Pruebas etiqueta"
task :spec do
   sh "rspec -I. spec/etiqueta_spec.rb"
end

desc "Pruebas lista"
task :spec do
   sh "rspec -I. spec/lista_spec.rb"
end

desc "Pruebas individuo"
task :spec do
   sh "rspec -I. spec/individuo_spec.rb"
end

desc "Pruebas array"
task :spec do
   sh "rspec -I. spec/array_spec.rb"
end